      SUBROUTINE ADDROT  (XNEW,I,
     $         LTOT,ZRAY,XCMF,OPARAY,ETARAY,OPALRAY,ETALRAY,S,RRAY,PJPJ)
C***********************************************************************
C***  CALLED FROM OBSFRAM
C***  INSERTION OF AN ADDITIONAL DEPTH POINT INTO A RAY
C***********************************************************************
      DIMENSION S(LTOT),OPARAY(LTOT),ZRAY(LTOT),XCMF(LTOT),RRAY(LTOT)
      DIMENSION OPALRAY(LTOT),ETARAY(LTOT),ETALRAY(LTOT)
 
      CALL SHIFT (ZRAY   ,I,LTOT)
      CALL SHIFT (RRAY   ,I,LTOT)
      CALL SHIFT (XCMF   ,I,LTOT)
      CALL SHIFT (OPARAY ,I,LTOT)
      CALL SHIFT (ETARAY ,I,LTOT)
      CALL SHIFT (OPALRAY,I,LTOT)
      CALL SHIFT (ETALRAY,I,LTOT)
      CALL SHIFT (S      ,I,LTOT)
C***  CUBIC INTERPOLATION OF ZNEW(XNEW)
      CALL CUBIC (I,LTOT,XCMF,ZRAY,P1,P2,P3,P4)
C***  EVALUATION OF THE CUBIC INTERPOLATION FOR Z
      ZIP1=ZRAY(I+1)
      ZIM1=ZRAY(I-1)
      XIP1=XCMF(I+1)
      XIM1=XCMF(I-1)
      ZNEW=(ZIP1+ZIM1)*0.5
      ZOLD=ZNEW
      ITER=0
    1 CONTINUE
      ITER=ITER+1
      IF (ITER.GT.60) THEN
         PRINT *,' ITER.GT.60 IN ADDSTEP'
         GOTO 2
      ENDIF
      DXA=ZNEW-ZRAY(I-1)
      DXB=ZRAY(I+1)-ZNEW
      DXA3=DXA*DXA*DXA
      DXB3=DXB*DXB*DXB
      XZNEW   =P1*DXA3+P2*DXA+P3*DXB3+P4*DXB
      DX=XZNEW-XNEW
      IF (ABS(DX).GT.1.E-4) THEN
      IF (ITER.GT.1) THEN
      DXA2=DXA*DXA
      DXB2=DXB*DXB
      DXDZN   =3.*P1*DXA2+P2-3.*P3*DXB2-P4
      ZOLD=ZNEW
      IF (DXDZN.NE.0.) THEN
      ZNEW=ZOLD-DX/DXDZN
      IF (ZNEW.GE.ZIP1.AND.ZNEW.LT.ZIM1) GOTO 1
      ENDIF
      ENDIF
      IF ((XIP1     -XNEW)*DX.LT.0.) THEN
         DZ=ZIP1-ZOLD
         DXFR=DX/(XZNEW-XCMF(I+1))
         ZIM1=ZOLD
         XIM1=XZNEW
      ELSE IF ((XIM1     -XNEW)*DX.LT.0.) THEN
         DZ=ZIM1-ZOLD
         DXFR=DX/(XZNEW-XCMF(I-1))
         ZIP1=ZOLD
         XIP1=XZNEW
      ELSE
      DXDZN=0.
         GOTO 2
      ENDIF
      ZNEW=ZOLD+DZ*DXFR
      IF (ZNEW.GE.ZIP1.AND.ZNEW.LT.ZIM1) GOTO 1
      PRINT *,I,XNEW,P1,P2,P3,P4,ITER,ZNEW,ZOLD,DZ,DX,DXFR,XZNEW,DXDZN
      PRINT *, (I,ZRAY(I),XCMF(I),I=1,LTOT)
      STOP ' WRONG-2'
      ENDIF
 
      ZRAY(I)=ZNEW
      XCMF(I)=XNEW
C***  INTERPOLATION OF OPACITIES ETC.: LINEAR IN RADIUS R
      RNEW=SQRT(PJPJ+ZRAY(I)*ZRAY(I))
      RRAY(I)=RNEW
      P=(RNEW-RRAY(I-1))/(RRAY(I+1)-RRAY(I-1))
      Q=1.-P
C***  INTERPOLATION WEIGHTS MODIFIED: LINEAR INTERPOLATION IN R**2
      Q=Q*RRAY(I-1)*RRAY(I-1)/(RNEW*RNEW)
      P=P*RRAY(I+1)*RRAY(I+1)/(RNEW*RNEW)
      OPARAY (I)=Q*OPARAY (I-1)+P*OPARAY (I+1)
      ETARAY (I)=Q*ETARAY (I-1)+P*ETARAY (I+1)
      OPALRAY(I)=Q*OPALRAY(I-1)+P*OPALRAY(I+1)
      ETALRAY(I)=Q*ETALRAY(I-1)+P*ETALRAY(I+1)
      S      (I)=Q*S      (I-1)+P*S      (I+1)
      LTOT=LTOT+1
      RETURN
C***  ERROR STOP
    2 PRINT *,I,XNEW,P1,P2,P3,P4,ITER,ZNEW,ZOLD,DZ,DX,DXFR,XZNEW,DXDZN
      PRINT *, (I,ZRAY(I),XCMF(I),I=1,LTOT)
      ZNEW=DX/DXDZN
         STOP ' S.T. WRONG'
      END
