      SUBROUTINE CHANGE (NAMEOLD, NAMENEW, ICHANNEL)
C***  THIS SUBROUTINE REPLACES A NAME IN THE NAME-INDEX ARRAY IADR
C***  OF A MASS-STORAGE FILE

        CALL CMSSTORE (ICHANNEL, IDUMMY, IDUMMY, NAMEOLD, NAMENEW, 
     >                 DUMMY, NDUMMY, 'CHANGE', IERR)

      RETURN
      END
