      SUBROUTINE COFREQ (XR,XB,XMAX,ERXMIN,GDT,THIN)
C***  CALCULATES THE CONFINING FREQUENCIES XR AND XB FOR ONE DIRECTION
      COMMON / COMFUN / DELTAV,XMIN
      LOGICAL THIN
      EXTERNAL FUNSCH,ERF
C***  EPS = ACCURACY DEMAND FOR REGULA
      DATA  EPS / 1.E-3 /
 
      IF (GDT .GE. 1.-2.*ERXMIN ) GOTO 3
      THIN=.FALSE.
C***  FOR INNER POINTS : 
      ERFXR=GDT+ERXMIN
      CALL REGULA (ERF   ,XR,ERFXR,-XMAX,XMAX,EPS)
      XB=XMAX
 
      IF (XR+XMAX .LE. DELTAV) RETURN
C***  BOUNDARY ZONE
         DV2=DELTAV/2.
C***     OPTICAL THIN CASE
         IF (GDT .GE. 2.*(ERF(DV2)-ERXMIN)-1.) GOTO 3
         XMIN=-XMAX
         CALL REGULA (FUNSCH,XR,GDT,XR-EPS,DV2,EPS)
         XB=DELTAV-XR
      RETURN
 
C***  OPTICAL THIN CASE
    3 THIN=.TRUE.
      XR=.0
      XB=.0
      RETURN
      END
