C***  This replaces the COMMON block VELOTABLE
      MODULE COMVELOTABLE

      INTEGER :: MAXTABLE, NTABLE
      PARAMETER (MAXTABLE = 2000)
      LOGICAL :: bVELOTABLE
      REAL    :: FSONICTA, FSONICTA_CARDS
      REAL, DIMENSION(MAXTABLE) :: RTABLE, VTABLE

      END MODULE COMVELOTABLE

