      FUNCTION DELPLA (T)
C***  THIS FUNCTION IS USED BY SUBR. PRIFLUX FOR THE ESTIMATE OF TCOLOR
C***  AND CALCULATES THE RATIO B-NUE(XLAM1,T) /  B-NUE(XLAM2,T)
      COMMON / COMDPL / XLAM1, XLAM2
      DELPLA=BNUE(XLAM1,T)/BNUE(XLAM2,T)
      RETURN
      END
