      SUBROUTINE OPAROSS (OPARL,EN,TL,RNEL,ENTOTL,RSTAR,NDIM,N,
     $                   LEVEL,NCHARG,WEIGHT,ELEVEL,EION,EINST,
     $                   ALPHA,SEXPO,
     $                   ADDCON1, ADDCON2, ADDCON3, 
     $                   IGAUNT,NF,XLAMBDA,FWEIGHT,NOM,
     $                   MAXATOM,SIGMATHK,SEXPOK,EDGEK,KODAT,RL,
     $                   KONTNUP,KONTLOW,LASTKON)
C***********************************************************************
C***  COMPUTATION OF THE ROSSELAND MEAN OPACITY AT DEPTH POINT L
C***  FOR GIVEN POPNUMBERS
C***********************************************************************
 
      DIMENSION EINST(NDIM,NDIM)
      DIMENSION EN(NDIM)
      DIMENSION NCHARG(N),WEIGHT(N),ELEVEL(N),EION(N)
      DIMENSION XLAMBDA(NF),FWEIGHT(NF)
      CHARACTER*10 LEVEL(N),MAINPRO,MAINLEV
 
C***  FREQUENCY INTEGRATION ***
C***  NOTE: FOR NUMERICAL REASONS, THE NORMALIZATION CONSTANT Q IS
C**     ALSO INTEGRATED NUMERICALLY!
      SUM=.0
      Q=.0
C***  USE INTEGER VARIABLE 'LYMP' INSTEAD OF INTEGER CONSTANT "1" 
C***  (OLD VERSION) TO PREVENT RUNTIME ABORT ON Y-MP SYSTEMS
C***  (cft77 5.0.5.0 OR segldr 8.0c ERROR???)
C***  [ U. WESSOLOWSKI, 29-SEP-1993 20:39:49 ]
      LYMP = 1
      DO 1 K=1,NF
      XLAM=XLAMBDA(K)
      CALL COOP (XLAM,LYMP,TL,RNEL,EN,ENTOTL,RSTAR,OPA,ETA,THOMSON,
     $          IWARN,MAINPRO,MAINLEV,NOM,KODAT,NDIM,N,MAXATOM,
     $          LEVEL,NCHARG,WEIGHT,
     $          ELEVEL,EION,EINST,ALPHA,SEXPO,
     $          ADDCON1, ADDCON2, ADDCON3, 
     $          IGAUNT,SIGMATHK,SEXPOK,EDGEK,0,DUMMY,DUMMY,RL,
     $          KONTNUP,KONTLOW,LASTKON,0.)
C***  DERIVATIVE OF THE PLANCK FUNCTION WITH RESPECT TO T
      DBDT=DBNUEDT(XLAM,TL)
      SUM=SUM+DBDT*FWEIGHT(K)/OPA
      Q=Q+DBDT*FWEIGHT(K)
    1 CONTINUE
 
      OPARL=Q/SUM      

      RETURN
      END
