      SUBROUTINE TCOLOR (XL1,XL2,EM1,EM2,ITCOL)
C***********************************************************************
C***  CALCULATION OF TCOLOR FROM THE SLOPE OF EMFLUX BETWEEN XLAM1 AND XLAM2
C***********************************************************************

C***  COMMON /COMDPL / IS USED BY FUNCTION DELPLA (RATIO OF PLANCK FUNCTIONS)
      COMMON / COMDPL / XLAM1, XLAM2
C*** FUNCTION DELPLA IS FORMAL PARAMETER IN SUBR. REGULA
      EXTERNAL DELPLA
C***  TCOL1,TCOL2 = MIN AND MAX COLOUR TEMPERATURE TO BE DETERMINED
C***  EPS = ACCURACY OF TCOLOR DETERMINATION
      DATA TCOL1,TCOL2,EPS/1000.,500000.,50./

      CHARACTER*8 ITCOL   

      XLAM1=XL1
      XLAM2=XL2
         ITCOL='   UNDEF'
         BMIN=BNUE(XLAM2,TCOL1)
         IF (BMIN.GT.0.) THEN
          IF (EM2 .GT. .0) THEN
            DFK=EM1/EM2
            DFKMIN=BNUE(XLAM1,TCOL1)/BNUE(XLAM2,TCOL1)
            DFKMAX=BNUE(XLAM1,TCOL2)/BNUE(XLAM2,TCOL2)
            IF (DFK.LT.DFKMAX.AND.DFK.GT.DFKMIN) THEN
               CALL REGULA (DELPLA,TCOL,DFK,TCOL1,TCOL2,EPS)
cc               ENCODE (8,10,ITCOL) TCOL
cc   10          FORMAT (F8.0)
               WRITE (ITCOL, '(F8.0)') TCOL
            ENDIF
          ENDIF
        ENDIF
      RETURN
      END
